package com.example.Mapper;

import com.example.Pojo.Teach;
import com.example.Pojo.TeachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    long countByExample(TeachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    int insertSelective(Teach row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    List<Teach> selectByExample(TeachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    Teach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    int updateByExampleSelective(@Param("row") Teach row, @Param("example") TeachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    int updateByExample(@Param("row") Teach row, @Param("example") TeachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    int updateByPrimaryKeySelective(Teach row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    int updateByPrimaryKey(Teach row);
}