package com.example.Pojo;

public class Teach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teach.id
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teach.name
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teach.age
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teach.id
     *
     * @return the value of teach.id
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teach.id
     *
     * @param id the value for teach.id
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teach.name
     *
     * @return the value of teach.name
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teach.name
     *
     * @param name the value for teach.name
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teach.age
     *
     * @return the value of teach.age
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teach.age
     *
     * @param age the value for teach.age
     *
     * @mbg.generated Wed Jan 21 13:58:02 CST 2026
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "Teach{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }
}